name: 'setup-machine'
description: 'Prepares the machine for build (setup gradle, jdk etc)'
runs:
  using: "composite"
  steps:
    - name: "Setup JDK 8 for tools.jar"
      id: setup-java8
      uses: actions/setup-java@v1
      with:
        java-version: "8"
    - name: "set tools jar path"
      id: setup-tools-jar
      shell: bash
      run: |
        set -x
        TOOLS_JAR=$JAVA_HOME/lib/tools.jar
        echo "::set-output name=toolsJar::$TOOLS_JAR"
    - name: "Setup JDK 11"
      id: setup-java
      uses: actions/setup-java@v1
      with:
        java-version: "11"
    # TODO b/216535050: Implement task to install the exact AndroidX ndk
    # version in case it is not available.
    - name: "Install Cmake"
      shell: bash
      run: echo "yes" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "cmake;3.22.1" --channel=3
    - name: "Set environment variables"
      shell: bash
      run: |
        set -x
        echo "DIST_DIR=$HOME/dist" >> $GITHUB_ENV

    - name: "Setup Gradle"
      uses: gradle/gradle-build-action@v2
      with:
        # Only save Gradle User Home state for builds on the 'androidx-main' branch.
        # Builds on other branches will only read existing entries from the cache.
        cache-read-only: ${{ github.ref != 'refs/heads/androidx-main' }}

        # Don't reuse cache entries from any other Job.
        gradle-home-cache-strict-match: true

        # Limit the size of the cache entry.
        # These directories contain instrumented/transformed dependency jars which can be reconstructed relatively quickly.
        gradle-home-cache-excludes: |
          caches/jars-9
          caches/transforms-3
    - name: Decide Gradle Version
      id: decide-gradle-version
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          // decide which gradle version to use.
          // if there is an input, use that
          if (github.event.inputs.gradle-version != null) {
            return github.event.inputs.gradle-version
          }
          // if it is scheduled build, use release-nightly
          if (github.event.schedule != null) {
            return "release-nightly"
          }
          return ""

    - name: "Modify Gradle Version"
      shell: bash
      if: ${{ steps.decide-gradle-version.outputs.result != '' }}
      run: |
        python3 playground-common/set-gradle-version.py ${{ steps.decide-gradle-version.outputs.result }}
