name: 'build-single-playground-project'
description: 'Builds one playground project based on inputs'
inputs:
  project:
    description: "Name of the project (used for artifacts)"
    required: true
  project-root:
    description: "Root folder of the project (used for building)"
    required: true
  gradle-cache-password:
    description: "password for gradle cache"
  gradle-enterprise-access-key:
    description: "access key for gradle enterprise"
  gradle-flags:
    description: "flags to pass while invoking gradle"
runs:
  using: "composite"
  steps:
    - name: "setup machine"
      uses: ./.github/actions/build-single-project

    - name: "gradle buildOnServer zipTestConfigsWithApks test"
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.path }}
        JAVA_TOOLS_JAR: ${{ steps.setup-tools-jar.outputs.toolsJar }}
        GRADLE_BUILD_CACHE_PASSWORD: ${{ inputs.gradle-cache-password }}
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ inputs.gradle-enterprise-access-key }}
      working-directory: ${{ inputs.project-root }}
      shell: bash
      run: ./gradlew buildOnServer zipTestConfigsWithApks test ${{ inputs.gradlew_flags }}
