name: Manually Run Integration Tests
on:
  push:
  workflow_run:
    workflows: ["AndroidX Presubmits"]
    types: [completed]

jobs:
  run_integration_tests:
    runs-on: ubuntu-latest
    name: Run integration tests on FTL
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: "set output directory"
        run: echo "::set-output name=output-dir::$(readlink -f .)/outputs"
        id: dirs
      - id: run_tests
        uses: androidX/androidx-ci-action@dist-v0.11
        with:
          target-run-id: 4896435090
          gcp-token: ${{ secrets.GCP_SA_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-folder: ${{ steps.dirs.outputs.output-dir }}
          gcp-bucket-name: "androidx-ftl-test-results"
          gcp-bucket-path: "github-ci-action"
          log-file: ${{ steps.dirs.outputs.output-dir }}/ftl-logs.txt
          device-specs: Pixel2.arm:30
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: outputs
          path: ${{ steps.dirs.outputs.output-dir }}
