name: Run Integration Tests
on:
  workflow_run:
    workflows: ["AndroidX Presubmits"]
    types: [completed]

jobs:
  run_integration_tests:
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.fork && github.event.workflow_run.conclusion == 'success' }}
    name: Run integration tests on FTL
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: "set output directory"
        run: |
          echo "::set-output name=output-dir::$(readlink -f .)/outputs"
          echo "::set-output name=log-file::$(readlink -f .)/ftl.logs"
        id: dirs
      - id: run_tests
        uses: androidX/androidx-ci-action@dist-v0.08
        with:
          target-run-id: ${{ github.event.workflow_run.id }}
          gcp-token: ${{ secrets.GCP_SA_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-folder: ${{ steps.dirs.outputs.output-dir }}
          log-file: ${{ steps.dirs.outputs.log-file }}
          artifact-name-filter-regex: ".*apks"
          gcp-bucket-name: "androidx-ftl-test-results"
          gcp-bucket-path: "github-ci-action"
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: outputs
          path: ${{ steps.dirs.outputs.output-dir }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: logs
          path: ${{ steps.dirs.outputs.log-file }}
  teardown:
    runs-on: ubuntu-latest
    needs: [run_integration_tests]
    if: ${{ !github.event.repository.fork && always() }} # always() is required so that this job will run irrespective of status of upstream 'run_integration_test' job.
    steps:
      - name: Parse workflow status
        id: workflow-status
        run: |
          set -x
          if [ "${{ needs.run_integration_tests.result }}" == "success" ]                  && \
            [ "${{ github.event.workflow_run.conclusion }}" == "success" ]
          then
            echo "::set-output name=result::true"
          else
            echo "::set-output name=result::false"
          fi

      - name: Result WebHook
        uses: androidx/github-workflow-webhook-action@main
        with:
          url: 'https://androidx.dev/github/androidX/presubmit/hook'
          secret: ${{ secrets.ANDROIDX_PRESUBMIT_HOOK_SECRET }}
          payload: '{ "platform": "all", "token": "${{ secrets.GITHUB_TOKEN }}", "state": "completed", "success": ${{ steps.workflow-status.outputs.result }}, "src" : "workflow_run" }'
